### ISSUE TITLE
Suggestion: faster way to get direction between 0 and 360

### ISSUE THREAD

**Issue by JakobTischler** [DeckerMMIV/FarmSim_Mod_Compass#3]
You're using two while loops in draw() to get the angle to be between 0 and 360. This can be achieved a lot faster by using modulo (`n % 360`):

```lua
local testDegrees = { -360, -30, 30, 361, 750, 0, 360 };
for _,deg in ipairs(testDegrees) do
	local res = deg % 360;
	print(('%+.3d -> %.3d'):format(deg, res));
end;

--[[ result:
-360 -> 000
-030 -> 330
+030 -> 030
+361 -> 001
+750 -> 030
+000 -> 000
+360 -> 000
]]
```

**Comment by DeckerMMIV** [comment]
I've been using C/C++ too much, to think of the '%' modulo-operator as only working on integer values, which is why I used the while-loops, as I wanted one digit of the fraction too.

But now I can see (just tested it), that LUA's % operator actually works on floating-point values; -1.33 % 360 = 358.67

Thank you for 'nudging me' into actually test the modulo operator with floating-point ;-)

**Comment by JakobTischler** [comment]
No worries. This was purely out of self-interest, as I use a "restrict to 0 - 360" function myself.
