### ISSUE TITLE
not loading the old position

### ISSUE THREAD

**Issue by mngrazy** [DeckerMMIV/FarmSim_Mod_Compass#4]
hi decker

Compass v 2.0.5 dont load the old position when i restart the game
i change the position with Alt+C to "BelowClock" ,,, after reloading my savegame the position is always on the "default" position

regards grazy

**Comment by DeckerMMIV** [comment]
The `Compass_Config.xml` will only be saved when you quit a game-session successfully.

If there is some other mods that causes the game's base scripts to not call `Compass.deleteMap()` - by either causing a failure or directly crashing FS15 - then the file won't (can't) be saved.

Or maybe - which I find more likely - the problem could be, because the screen aspect-ratio you are using, produces a floating-point number that can not be correctly represented as a string-value. - When Compass mod loads its `Compass_Config.xml`, it checks if the game's current aspect-ratio value is the same as last stored in the config-file. If these values are just slightly different (maybe by +/-0.00000001), then my script "thinks" that you probably have changed your screen-resolution, and will then re-generate new preset positions. - Maybe this "check" wasn't such a good idea.

So what screen-resolution are you using?

**Comment by mngrazy** [comment]
hi decker

the config.xml is correct , the position in the xml is <preset name="BelowClock" selected="true"......
i have no crash or bugs when i close my current game

and my resolution is 1920x1080

regards mngrazy

**Comment by DeckerMMIV** [comment]
Try using the latest code - v2.0.6 - and tell me if it solved the problem.

**Comment by mngrazy** [comment]
working ! loads the old position !

thank you decker for the fast solution ;)

regards grazy
